"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from dotenv import load_dotenv
import os
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv(override=True)

# SECURITY - IN PRODUZIONE METTI A TRUE, LEVA I COMMENTI E LASCIA DEBUGA A FALSE:

# this key is used for csrf_token protection
SECRET_KEY = os.getenv("SECRET_KEY")

SECURE_SSL_REDIRECT = False # if is True all the HTTP request will be automatically converted in HTTPS
SECURE_SESSION_COOCKIE=False # Il cookie della sessione viene inviato solo su HTTPS.
CSRF_COOKIE_SECURE = False # il coockie CSRF viene inviato solo su HTTPS

# previene l'accesso ai coockie via JS (protezione contro XSS)
SESSION_COOKIE_HTTPONLY = False
CSRF_COOKIE_HTTPONLY = False

SECURE_BROWSER_XSS_FILTER = False # abilità filtro XSS nel browser
# X_FRAME_OPTIONS = 'DENY' # impedisce che il sito sia incorporato in iframe -> clickjacking

SECURE_HSTS_SECONDS = 0 # valore in secondi per cui il browser ricorderà di usare solo HTTPS per il sito
SECURE_HSTS_INCLUDE_SUBDOMAIN = False # opz. per includere i subdomain
SECURE_HSTS_PRELOAD = False # opz. preload dei browser

# DEBUG = config('DEBUG', default=True, cast=bool)
DEBUG = False

# if debug = false, must have allowed_hosts on
# solo i domini elencati posso accedere al sito
ALLOWED_HOSTS = [
    "*", # all
]

ADMIN_PATH = 'user-bruno/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    #'hide_admin.apps.HideAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # pesronal apps
    'core', # used for the search logic
    'api', # used only for endpoints

    # rest-framework
    'rest_framework',
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
}

# if DEBUG is true shows JSON data + the auto-html page test
if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
        "rest_framework.renderers.BrowsableAPIRenderer"
    )
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

RESTRICT_ADMIN = True
ALLOWED_ADMIN_IPS = ['127.0.0.1'] # add IP able to connect to admin page

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME','macchine'), 
        'USER': os.getenv('DB_USERNAME'), 
        'PASSWORD': os.getenv('DB_PASSWORD'), 
        'HOST': os.getenv('DB_IP','127.0.0.1'),
        'PORT': os.getenv('DB_PORT'),
        "OPTIONS": {
            # resolve data validation problems
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

DATA_ROOT = BASE_DIR / "database" / "json"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#'''
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR/'static'
]
'''
STATIC_URL = 'staticfiles/'
STATICFILES_DIRS = [
    BASE_DIR/'staticfiles'
]
#'''

# STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files serving without Ngingx
STORAGES = {
    "staticfiles":{
        "BACKEND":"whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
}