# Generated by Django 6.0.3 on 2026-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'api_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRequestLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_request_logs',
                'permissions': [('puo_accedere', 'Puo archiviare i dati e fare richieste')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreRequestLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_request_logs',
                'ordering': ['-created_at', 'endpoint'],
                'managed': False,
            },
        ),
    ]
