# Generated by Django 6.0.3 on 2026-03-11 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allarmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255, unique=True)),
                ('descrizione', models.TextField()),
                ('text_it', models.TextField()),
                ('text_eng', models.TextField()),
                ('text_esp', models.TextField(null=True)),
                ('text_de', models.TextField(null=True)),
                ('text_fr', models.TextField(null=True)),
                ('text_dk', models.TextField(null=True)),
                ('text_pt', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
            options={
                'db_table': 'allarmi_soluzioni',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Componenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codicefb', models.CharField(db_column='codiceFB', max_length=255, unique=True)),
                ('cod_gestionale', models.CharField(max_length=255, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=128)),
                ('quantita', models.IntegerField()),
            ],
            options={
                'db_table': 'componenti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatiCilindri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dati_cilindri',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatiMotori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dati_motori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatiRiduttori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dati_riduttori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Macchinari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piano_produzione', models.CharField(max_length=128, unique=True)),
                ('categoria', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=128)),
                ('tipo_plc', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'macchinari',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manutenzioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_manutenzione', models.CharField(max_length=128, unique=True)),
                ('tipo', models.CharField(max_length=128)),
                ('cosa_fare', models.TextField()),
                ('priorita', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'manutenzioni',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Informazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluzione_problema', models.TextField()),
                ('path_img', models.CharField(max_length=255, unique=True)),
                ('path_video', models.CharField(max_length=255, unique=True)),
                ('id_allarme', models.ForeignKey(db_column='id_allarme', on_delete=django.db.models.deletion.DO_NOTHING, to='core.allarmi')),
                ('id_componente', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.componenti')),
                ('id_macchinario', models.ForeignKey(db_column='id_macchinario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.macchinari')),
            ],
            options={
                'db_table': 'informazioni',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatiManutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cilindro', models.ForeignKey(db_column='id_cilindro', on_delete=django.db.models.deletion.DO_NOTHING, to='core.daticilindri')),
                ('id_motore', models.ForeignKey(db_column='id_motore', on_delete=django.db.models.deletion.DO_NOTHING, to='core.datimotori')),
                ('id_riduttore', models.ForeignKey(db_column='id_riduttore', on_delete=django.db.models.deletion.DO_NOTHING, to='core.datiriduttori')),
                ('id_macchinario', models.ForeignKey(db_column='id_macchinario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.macchinari')),
            ],
            options={
                'db_table': 'dati_manutenzione',
                'managed': True,
            },
        ),
    ]
