# Generated by Django 6.0.3 on 2026-03-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatiCilindri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dati_cilindri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatiManutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dati_manutenzione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatiMotori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dati_motori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatiRiduttori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dati_riduttori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manutenzioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_manutenzione', models.CharField(max_length=128, unique=True)),
                ('tipo', models.CharField(max_length=128)),
                ('cosa_fare', models.TextField()),
                ('priorita', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'manutenzioni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
