# Generated by Django 6.0.3 on 2026-03-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenti',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datimotori',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datiriduttori',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='informazioni',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='macchinari',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='manutenzioni',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
