import json

#path = r'C:\Users\loren\Desktop\GitHub\WebCore\project\script\json\test_scrittura.json'
path = r'C:\Users\loren\Desktop\GitHub\WebCore\project\allarmi_soluzioni_backup.json'
with open(path, 'r') as file:
    json_dict: dict = json.load(file)
#
'''
update_key1 = 'json_update'
update_key2 = 'db_update'

json_dict[update_key1] = 'false'
json_dict[update_key2] = 'false'

with open(path,'w') as file:
    json_dict = json.dump(json_dict, file, indent=4)
'''

# aggiunta dati

for i in range(1, 1001, 1):

    titolo_allarme = f"allarme{i}"

    json_dict["lista_allarmi"][titolo_allarme] = {
            "media":{
                "video":{
                    "nome_file":"video_sensore",
                    "path_file":"\\videos\\video_sensore.mp4"
                    },
                "img":{
                    "nome_file":"sensore_laser",
                    "path_file":"\\images\\sensore_laser.png"
                    }
                },
            "testo_soluzione":{
                    "it" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "eng" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "esp" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "de" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "fr" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "dk" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "pt" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "ru" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "pl" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "no" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina.",
                    "se" : "Quasi tutto l'Iran è stato distrutto e l'esercito americano sta continuando a colpire Teheran molto duramente. Così Donald Trump sintetizza, ancora una volta, l'andamento della guerra in corso contro la Repubblica islamica. In un intervista ad Axios, il presidente degli Stati Uniti ha poi detto che il conflitto finirà presto, anche perché non c'è praticamente niente più da bombardare (IL RACCONTO DELLA GIORNATA). Poi ha aggiunto: Siamo molto in anticipo sui tempi previsti. Abbiamo causato più danni di quanto pensassimo possibile, anche nel periodo iniziale di sei settimane. Quando finirà quindi? Quando voglio che finisca, finirà, dice Trump. Parlando con i giornalisti in Ohio, poi, aggiunge: la guerra in Iran è stata più semplice del previsto. E assicura: Il prezzo del petrolio calerà. Poi l'annuncio: il presidente ha detto che intende prelevare un po di petrolio dalle riserve americane per contrastare l'aumento dei prezzi della benzina."
            }            
    }

    with open(path, 'w+') as file:
        json.dump(json_dict, file, indent=4)
    
    print(f"step:[{i}]")
#'''

                