# Testing the API Endpoint 

# POST request with REST-Client extension

POST 192.168.77.55/requests/info HTTP/1.1
Content-Type: : application/json

{
    "client_key": "api-key-test0",
    "language": "text_esp",
    "machine_code": "29430",
    "machine_type": "1200",
    "machine_alarm": "dio____"
}