# niente spazio tra POST e content-type e altri 
# solo tra body e header cioè quello sopra
# X-XSRF-TOKEN: {{$xsrf-token}}

POST http://127.0.0.1:8000/request/info/ 
Content-Type: application/json
Authorization: {{$xsrf-token}}

{
    "client_key": "api-key-test0",
    "language": "text_it",
    "machine_code": "pp23274",
    "machine_type": "1200",
    "machine_alarm": "allarme908"
}
